name: Build AppImage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake qtbase5-dev qt5-qmake wget

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Download linuxdeployqt
        run: |
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage

      - name: Build AppImage
        run: |
          ./linuxdeployqt-continuous-x86_64.AppImage build/ROS2_Automatic_Installer-aarch64 -appimage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: ./*.AppImage
